# Filename: tide_harmonics_library_generator.R
# Extract harmonics constituents for a single tide station to be used 
# elsewhere. The harmonics Rdata file needs to have been generated by the 
# tide_harmonics_parse.R script already. 

# Author: Luke Miller  June 8, 2012
###############################################################################

# Load the previously-generated harmonics file that contains data for all 637
# reference sites in North America. These are only for tide reference stations 
# maintained by NOAA. NOAA generates predictions for a few thousand other 
# 'subordinate' stations that are not included in this data set. The subordinate
# station predictions are generally made by applying a height offset 
# correction and high/low tide time correction to the predictions from the local
# reference station. If you wish to make predictions for one of these 
# subordinate stations you'll still need to first generate predictions for the 
# local reference station (contained in this data set) and apply your 
# corrections afterwards.
load('Harmonics_20120302.Rdata')

# Specify a search string that will hopefully only return a single station
stationID = 'San Diego, San Diego Bay'
#stationID = 'Monterey Harbor'
#stationID = 'San Francisco'
#stationID = 'Port San Luis'
# Find row index of the desired station in the harms list
stInd = grep(stationID, harms$station)

#Remove spaces from station name so it can be used as a library name
libname = gsub('[ ]', '', stationID)
libname = gsub('[,]', '', libname)
libname = paste('Tide',libname,'lib',sep = '')

# We only want to hold on to starting constants for this year (and future years)
# so we'll get the year index for the current year so that we can dump data from
# earlier years
curr.date = as.POSIXlt(Sys.time())
curr.year = curr.date$year + 1900
year.ind = curr.year - harms$startyear + 1

# Specify number of years' worth of starting constants to keep
# More than 4 year's worth of constants starts to fill up the Arduino SRAM, and
# will not allow the program to run correctly.
keep.years = 10

# Extract the useful bits from the harms list, keeping only data for the 
# desired tide station.
# NOAA generally reports 37 harmonic constituents for a tide station on their 
# site. These correspond to the first 37 constants listed in the XTide harmonics
# file, and all of the names match up except LDA2 (called LAM2 by NOAA). So we
# can just keep the first 37 constants instead of all 175 from the XTide file.
# These will give predictions that are well within the variance in tide height
# caused by local day-to-day weather conditions. Note that the order of the 
# named constituents differs between the XTide harmonics file and the NOAA 
# web pages.
harms1 = list(name = harms$name[1:37], 
		speed = harms$speed[1:37],
		startyear = seq(curr.year, (curr.year+keep.years-1)),
		equilarg = harms$equilarg[1:37, year.ind:(year.ind+keep.years-1)],
		nodefactor = harms$nodefactor[1:37, year.ind:(year.ind+keep.years-1)],
		station = harms$station[stInd],
		units = harms$units[stInd],
		longitude = harms$longitude[stInd],
		latitude = harms$latitude[stInd],
		timezone = harms$timezone[stInd],
		tzfile = harms$tzfile[stInd],
		datum = harms$datum[stInd],
		A = harms$A[stInd,1:37],
		kappa = harms$kappa[stInd,1:37])

attr(harms1$equilarg, 'dimnames')[[1]] = harms1$name
attr(harms1$equilarg, 'dimnames')[[2]] = harms1$startyear
attr(harms1$nodefactor, 'dimnames')[[1]] = harms1$name
attr(harms1$nodefactor, 'dimnames')[[2]] = harms1$startyear
#########################################################
# Calculate starting values for subsequent years relative to unix epoch
yr.start = seq(curr.year, (curr.year + keep.years -1))
yr.unix = as.numeric(as.POSIXct(paste(yr.start,"1","1",sep = '-'))) - 
		as.numeric(as.POSIXct('1970-1-1'))

# generate some file names etc. 
libnamecpp = paste(libname,'.cpp',sep = '')
libnameh = paste(libname, '.h', sep = '')
libdirname = paste('./',libname, sep = '')
# Create a directory to hold the library output files
dir.create(libdirname)
# Begin sending output to a .cpp source file
sink(file = paste(libdirname,libnamecpp, sep = '/'), type = 'output', 
		split = TRUE, append = FALSE)

cat('/* ', libnamecpp, '\n')
cat(' This source file contains a tide calculation function for the site listed\n')
cat(' below. This file and the associated header file should be placed in the\n')
cat(' Ardiuno/libraries/ directory inside a single folder.\n')
cat(' Luke Miller, June 2012\n')
cat(' Released under the GPL version 3 license.\n')
cat(' The harmonic constituents used here were originally derived from \n')
cat(' XTide, available at http://www.flaterco.com/xtide/files.html\n')
cat(' The predictions from this program should not be used for navigation\n')
cat(' and no accuracy or warranty is given or implied for these tide predictions.\n')
cat(' */\n')
cat('#include <Arduino.h>\n')
cat('#include <Wire.h>\n')
cat('#include <avr/pgmspace.h>\n')
cat('#include "RTClib.h"\n')
cat('#include "', libnameh,'"\n\n', sep = '')
cat('unsigned int YearIndx = 0; // Used to index rows in the Equilarg/Nodefactor arrays\n')
cat('float currHours = 0;          // Elapsed hours since start of year\n')
cat('const int adjustGMT = 8;     // Time zone adjustment to get time in GMT.\n')
cat('//Make sure this is correct for the local standard time of the tide station.\n')
cat('// 8 = Pacific Standard Time (America/Los_Angeles)\n')
cat('/* Initialize harmonic constituent arrays. These each hold 37 values for\n')
cat('the tide site that was extracted using the R scripts:\n')
cat('tide_harmonics_parse.R and tide_harmonics_library_generator.R\n\n')
cat("The values are available from NOAA's http://tidesandcurrent.noaa.gov site.\n")
cat("Kappa here is referred to as 'Phase' on NOAA's site. The order of the\n")
cat('constituents is shown below in the names. Unfortunately this does not match\n')
cat("NOAA's order, so you will have to rearrange NOAA's values if you want to\n")
cat('put new site values in here by hand.\n')
cat('The Speed, Equilarg and Nodefactor arrays can all stay the same for any site.\n')
cat('*/\n\n')

cat('// Selected station: ', harms1$station,'\n')
cat('char stationID[] = "', harms1$station,'";\n')
cat("// The 'datum' printed here is the difference between mean sea level and \n") 
cat("// mean lower low water for the NOAA station. These two values can be \n") 
cat("// found for NOAA tide reference stations on the tidesandcurrents.noaa.gov\n")
cat("//  site under the datum page for each station.\n") 
cat('const float Datum =', harms1$datum, '; // units in feet\n')
cat('// Harmonic constant names: ')
cat(harms1$name, sep = ', ')
cat('\n')
cat("// These names match the NOAA names, except LDA2 here is LAM2 on NOAA's site\n")
cat("typedef float PROGMEM prog_float_t; // Need to define this type before use\n")
cat('PROGMEM prog_float_t Amp[] = {')
cat(harms1$A, sep = ',')
cat('};\n')
cat('PROGMEM prog_float_t Kappa[] = {')
cat(harms1$kappa, sep = ',')
cat('};\n')

cat('PROGMEM prog_float_t Speed[] = {')
cat(harms1$speed, sep = ',')
cat('};\n')

## Create code for a 4 year x 37 constituent array
cat('PROGMEM prog_float_t Equilarg[')
cat(keep.years)
cat('][37] = { \n')
for (i in 1:(ncol(harms1$equilarg)-1)) {
	cat('{')
	cat(harms1$equilarg[, i], sep = ',')
	cat('},\n')
}
cat('{')
cat(harms1$equilarg[ ,ncol(harms1$equilarg)], sep = ',')
cat('} \n };\n')
cat('\n')

cat('PROGMEM prog_float_t Nodefactor[')
cat(keep.years)
cat('][37] = { \n')
for (i in 1:(ncol(harms1$nodefactor)-1)) {
	cat('{')
	cat(harms1$nodefactor[, i], sep = ',')
	cat('},\n')
}
cat('{')
cat(harms1$nodefactor[ ,ncol(harms1$nodefactor)], sep = ',')
cat('} \n };\n')
cat('\n')

cat('// Define unix time values for the start of each year.\n')
cat('//                                      ')
cat(yr.start, sep = '       ')
cat('\n')
cat('PROGMEM prog_uint32_t startSecs[] = {')
cat(yr.unix, sep = ',')
cat('};\n\n')

cat('// 1st year of data in the Equilarg/Nodefactor/startSecs arrays.\n')
cat('const unsigned int startYear = ')
cat(yr.start[1], ';\n', sep = '')
cat('//------------------------------------------------------------------\n')
cat('// Define some variables that will hold extract values from the arrays above\n')
cat('float currAmp, currSpeed, currNodefactor, currEquilarg, currKappa, tideHeight;\n\n')
cat("// Constructor function, doesn't do anything special\n")
cat('TideCalc::TideCalc(void){}\n\n')
cat('// Return tide station name\n')
cat('char* TideCalc::returnStationID(void){\n')
cat('    return stationID;\n')
cat('}\n\n')
cat('// currentTide calculation function, takes a DateTime object from real time clock\n')
cat('float TideCalc::currentTide(DateTime now) {\n')
cat('	// Calculate difference between current year and starting year.\n')	
cat('	YearIndx = now.year() - startYear;\n ')
cat('	// Calculate hours since start of current year. Hours = seconds / 3600\n')
cat('	currHours = (now.unixtime() - pgm_read_dword_near(&startSecs[YearIndx])) / float(3600);\n')
cat('   // Shift currHours to Greenwich Mean Time\n')
cat('   currHours = currHours + adjustGMT;\n')
cat('   // *****************Calculate current tide height*************\n')
cat('   tideHeight = Datum; // initialize results variable, units of feet.\n')
cat('   for (int harms = 0; harms < 37; harms++) {\n')
cat('       currNodefactor = pgm_read_float_near(&Nodefactor[YearIndx][harms]);\n')
cat(' 		currAmp = pgm_read_float_near(&Amp[harms]);\n')
cat('       currEquilarg = pgm_read_float_near(&Equilarg[YearIndx][harms]);\n')
cat('       currKappa = pgm_read_float_near(&Kappa[harms]);\n')
cat('       currSpeed = pgm_read_float_near(&Speed[harms]);\n')
cat('    // Calculate each component of the overall tide equation\n')
cat('    // The currHours value is assumed to be in hours from the start of the\n')
cat('    // year, in the Greenwich Mean Time zone, not the local time zone.\n')
cat('       tideHeight = tideHeight + (currNodefactor * currAmp *\n')
cat('           cos( (currSpeed * currHours + currEquilarg - currKappa) * DEG_TO_RAD));\n')
cat('    }\n')
cat('    //******************End of Tide Height calculation*************\n')
cat('    return tideHeight;  // Output of tideCalc is the tide height, units of feet\n')
cat('}\n')
# Close the source file
sink()

# Open a header file for writing
sink(file = paste(libdirname,libnameh,sep = '/'), type = 'output', 
		split = TRUE, append = FALSE)
cat('/* ', libnameh,'\n')
cat('  A library for calculating the current tide height at \n')
cat('  ', harms1$station, '\n')
cat('  Luke Miller, June 2012\n')
cat('*/ \n \n')
libnameh2 = paste(libname, '_h', sep = '')
cat('#ifndef ', libnameh2, '\n')
cat('#define ', libnameh2, '\n')
cat('#include <Arduino.h>\n')
cat('#include <avr/pgmspace.h>\n')
cat('#include <Wire.h>\n')
cat('#include "RTClib.h"\n\n')
cat('class TideCalc {\n')
cat(' public:\n')
cat('	 TideCalc();\n')
cat('    float currentTide(DateTime now);\n')
cat('    char* returnStationID(void);\n')
cat('};\n')
cat('#endif')
sink()

# Create the keywords.txt file
sink(file = paste(libdirname,'keywords.txt', sep = '/'), type = 'output',
		split = TRUE, append = FALSE)
cat('TideCalc    KEYWORD1\n')
cat('currentTide    KEYWORD2\n')
cat('returnStationID KEYWORD2\n')
sink()
